### ISSUE TITLE
Create LODs rendereable entities manifest builder

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-explorer#211]
Implement a basic server to execute the scene runtime on a scene (or multiple) and output a JSON manifest file with its rendereable entities in the scene's initial state.

The instantiation of those meshes and the creation of the merged mesh (and LOD levels) is tackled in issue https://github.com/decentraland/unity-explorer/issues/40.

CURRENT SERVER IMPLEMENTATION AT https://github.com/decentraland/scene-lod-entities-manifest-builder

# TASKS
* [x] Implement remote scenes support
* [x] Implement SDK6 scenes support (adaption-layer/bridge)
* [x] Implement manifest output in JSON file instead of terminal printing
* [x] Implement support for editor-made scenes (instead of index.js they use crdt.main binary file)
* [x] Do a lot of cleanup of stuff we don’t need in the server codebase (since the lods-manifest-builder is based on the experimental scene-state-server)
* [x] Move the project to [its own repo](https://github.com/decentraland/scene-lod-entities-manifest-builder)
* [x] Implement optional overwrite logic, non-overwriting by default, as scenes change their scene-id on every deployment
* [x] Implement support for CLI commands to trigger the workflow
* [ ] Implement some exit-code logic for when we want to have this in a CI/Service
* [ ] Implement support for multiple scenes/coords as input
